FROM nginx
MAINTAINER Manickam<manickam.subramaniam@thoughtbees.com>
RUN apt-get update -qq && apt-get -y install apache2-utils
ENV RAILS_ROOT /var/www/braincarve
WORKDIR $RAILS_ROOT

RUN mkdir log 
COPY public public

COPY config/nginx.conf /tmp/default.nginx
 RUN envsubst '$RAILS_ROOT' < /tmp/default.nginx > /etc/nginx/conf.d/default.conf
EXPOSE 80
CMD [ "nginx", "-g", "daemon off;" ]